import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from './components/footer'
import Main from './components/main'
import Nav from './components/nav'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        {/* <html lang="en" /> */}
        <title>Fylo | landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Raleway:wght@400;700&display=swap" rel="stylesheet" />
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'></link>
      </Head>

      <header>
        <Nav />
      </header>
      <Main />
      <Footer />
    </div>
  )
}
